[icons]
# font awesome
TelegramDesktop = ""
firefox = ""
Alacritty = ""
kitty = ""
Thunderbird = ""
KeePassXC = ""
jetbrains-idea = ""
"TeamSpeak 3" = ""
"Portfolio Performance" = ""
"Yubico Authenticator" = ""
Pavucontrol = ""
Lutris = ""
Wine = ""
Steam = ""
discord = ""
Signal = ""
Spotify = ""

[general]
separator = " | "

[options]
remove_duplicates = true
